In [1]:
with open("lab4_textfile.txt",mode="w") as f:
    f.readlines()
f.close()

UnsupportedOperation: not readable

In [12]:
try:
    with open("lab4_textfile.txt",mode="w") as f:
        read_data = f.read()
        f.close()
except:
    print("Exception caught")
else:
    f.close()
finally:
    print("Cleaning up!")

Exception caught
Cleaning up!


In [37]:
class myException(Exception):
    

    def __init__(self,msg="This is my Exception class."):
        
        self.msg = msg
    

try:
    with open("lab4_textfile.txt",mode="w") as f:
        #read_data = f.read()
        f.close()
        raise myException
except myException as e:
    print(e.msg)
else:
    f.close()
finally:
    print("Cleaning up!")


This is my Exception class.
Cleaning up!


In [10]:
import numpy as np
b = np.arange(24).reshape(2,3,4)
print("Complete n-D Array")
print(b)
print("first set 0f 3X4")
print(b[0])
print("second row of data from the second set of 3 rows of data")
print(b[1][1])
print("all the data from the second column for both the first and second sets of rows and columns of data")
print(b[:,:,1])
print("############################################################################")
print(b[:,1,1])
myMatrix = np.arange(9).reshape(3,3)
myMatrix

Complete n-D Array
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
first set 0f 3X4
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
second row of data from the second set of 3 rows of data
[16 17 18 19]
all the data from the second column for both the first and second sets of rows and columns of data
[[ 1  5  9]
 [13 17 21]]
############################################################################
[ 5 17]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
flattened = b.flatten()
flattened

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [65]:
ravelled = np.ravel(b)
ravelled

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [70]:
b.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [87]:
print(b[0].transpose())
print(b[1].transpose())

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[12 16 20]
 [13 17 21]
 [14 18 22]
 [15 19 23]]


In [96]:
b_new=np.vstack((b[1].transpose(),b[0].transpose()))
b_new

array([[12, 16, 20],
       [13, 17, 21],
       [14, 18, 22],
       [15, 19, 23],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [98]:
split_array=np.hsplit(b_new,1)

In [104]:
for i in range(len(split_array[0])):
    print(split_array[0][i])

[12 16 20]
[13 17 21]
[14 18 22]
[15 19 23]
[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [40]:
import numpy as np
apple = np.loadtxt(fname="AAPL.csv",delimiter=',',usecols=(4,6),dtype=None,encoding="Utf8",skiprows=1)

Means :  32099381.430278886  192.0617928486056


In [46]:
close_price = apple[0:,0]
vol = apple[0:,1]
print("Means :",np.mean(avg_vol),np.mean(avg_close_price),sep="  ")
print("Median :",np.median(close_price),sep="  ")
print("Variance :",np.var(close_price),sep="  ")

Means :  32099381.430278886  192.0617928486056
Median :  197.0
Variance :  432.8804568188714


In [45]:
msft = np.loadtxt(fname="MSFT.csv",delimiter=',',usecols=(2,3),dtype=None,encoding="Utf8",skiprows=1)

In [48]:
high_price = msft[0:,0]
low_price = msft[0:,1]
print(max(high_price),min(low_price),sep=" ")

142.369995 93.959999


In [49]:
apple_5 = np.loadtxt(fname="AAPL.csv",delimiter=',',usecols=(4),dtype=None,encoding="Utf8",skiprows=1)
msft_5 = np.loadtxt(fname="MSFT.csv",delimiter=',',usecols=(4),dtype=None,encoding="Utf8",skiprows=1)

In [57]:
covariance = np.cov(apple_5,msft_5)
print(covariance)
print(covariance.diagonal())
corrcoef = np.corrcoef(apple_5,msft_5)
print(corrcoef)

[[434.60508015 186.97834783]
 [186.97834783 184.73421932]]
[434.60508015 184.73421932]
[[1.         0.65988802]
 [0.65988802 1.        ]]
